# Examle 03-23

$$\max Z = x_1 + 3x_2 + 3x_3$$


\begin{align*}
x_1 + 2x_2 + 3x_3 &= 4\\
2x_1 + 3x_2 + 5x_3 &= 7\\
x_1, x_2,x_3  &\geq 0
\end{align*}


  

In [1]:
from itertools import combinations
import numpy as np

In [2]:
z = np.array([1, 3, 3])

A = np.array([
    [1, 2, 3],
    [2, 3, 5],
])

b = np.array([4, 7])

In [4]:
print(A.shape)
num_constraints, num_variables = A.shape
print(num_constraints)

(2, 3)
2


In [7]:
list(range(num_variables))
print(list(combinations(range(num_variables),  num_constraints)))
print([*combinations(range(num_variables),  num_constraints)])

[(0, 1), (0, 2), (1, 2)]
[(0, 1), (0, 2), (1, 2)]


In [8]:
columns_index = [*combinations(range(num_variables),  num_constraints)]
print(columns_index)

[(0, 1), (0, 2), (1, 2)]


In [9]:
print(A)

[[1 2 3]
 [2 3 5]]


In [13]:
print(A[:, 0], '\n')

print(A[:, 1], '\n')

[1 2] 

[2 3] 



In [15]:
print(A[:, [0, 2]], '\n')

print(A[:, [1, 2]], '\n')

print(columns_index)

[[1 3]
 [2 5]] 

[[2 3]
 [3 5]] 

[(0, 1), (0, 2), (1, 2)]


In [19]:
print(columns_index, '\n')
print(columns_index[0], '\n')
print(columns_index[1], '\n')

[(0, 1), (0, 2), (1, 2)] 

(0, 1) 

(0, 2) 



In [21]:
print(A[:, [0, 1]], '\n')

print(A[:, columns_index[0]], '\n')

[[1 2]
 [2 3]] 

[[1 2]
 [2 3]] 



In [22]:
sys_eq01 = A[:, columns_index[0]]
sys_eq02 = A[:, columns_index[1]]
sys_eq03 = A[:, columns_index[2]]

In [23]:
print(len(columns_index))

3


In [24]:
print(sys_eq02)

[[1 3]
 [2 5]]


In [26]:
solution1 = np.zeros_like(z)
print(solution1)
solution2 = np.zeros_like(z)
solution3 = np.zeros_like(z)

[0 0 0]


In [28]:
print(columns_index)

[(0, 1), (0, 2), (1, 2)]


In [31]:
print(np.linalg.solve(sys_eq01, b))
print(np.linalg.solve(sys_eq02, b))
print(np.linalg.solve(sys_eq03, b))

[2. 1.]
[1. 1.]
[-1.  2.]


In [36]:
print(solution1)
print(np.linalg.solve(sys_eq01, b))  # x1, x2
print([*columns_index[0]])

print("Solution 1")
solution1[[*columns_index[0]]] = np.linalg.solve(sys_eq01, b)
print(solution1)

[2 1 0]
[2. 1.]
[0, 1]
Solution 1
[2 1 0]


In [37]:
print(f"Solution 2 before {solution2}")
print(f"Solution 3 before {solution3}")
print()
solution2[[*columns_index[1]]] = np.linalg.solve(sys_eq02, b)
solution3[[*columns_index[2]]] = np.linalg.solve(sys_eq03, b)

print(f"Solution 2 AFTER {solution2}")
print(f"Solution 3 AFTER {solution3}")

Solution 2 before [0 0 0]
Solution 3 before [0 0 0]

Solution 2 AFTER [1 0 1]
Solution 3 AFTER [ 0 -1  2]


In [38]:
print(solution1 >= 0 )

[ True  True  True]


In [40]:
print("Solution 2, is feasible?")
print(solution2 >= 0 )

Solution 2, is feasible?
[ True  True  True]


In [41]:
print("Solution 3, is feasible?")
print(solution3 >= 0 )

Solution 3, is feasible?
[ True False  True]


In [44]:
if (solution1 >= 0).all():
    print("Solution 1 is feasible")
else:
    print("Solution 1 is infeasible")

if (solution2 >= 0).all():
    print("Solution 2 is feasible")
else:
    print("Solution 2 is infeasible")

if (solution3 >= 0).all():
    print("Solution 3 is feasible")
else:
    print("Solution 3 is infeasible")

Solution 1 is feasible
Solution 2 is feasible
Solution 3 is infeasible


In [46]:
print(z.dot(solution1))

5


In [47]:
z.dot(solution2)


4

In [48]:
z.dot(solution3)

3

In [49]:
z1 = z.dot(solution1)
z2 = z.dot(solution2)

In [50]:
zvalues = [z1, z2]
print(zvalues)

[5, 4]


In [51]:
print(max(zvalues))

5


In [52]:
solutions = [solution1, solution2]
print(solutions)
print(zvalues)

[array([2, 1, 0]), array([1, 0, 1])]
[5, 4]


In [56]:
print([*enumerate(zvalues)])
print(max(enumerate(zvalues)))


[(0, 5), (1, 4)]
(1, 4)


In [57]:
print(max(enumerate(zvalues), key=lambda t:t[1]))

(0, 5)


In [58]:
best_index, best = max(enumerate(zvalues), key=lambda t:t[1])

In [59]:
print(best_index)

0


In [60]:
print(best)

5


In [61]:
print(solutions)

[array([2, 1, 0]), array([1, 0, 1])]


In [62]:
best_solution = solutions[best_index]
print(best_solution)

[2 1 0]


In [63]:
print(f'Optimal solution found at {best_solution} with zvalue: {best}')

Optimal solution found at [2 1 0] with zvalue: 5
