# Example 03-32

$$\max Z = 2x_1 + x_2 $$

\begin{align*}
x_1 + 2x_2  &\leq 10\\
        x_1 + x_2  &\leq 6\\
        x_1 - x_2  &\leq 2\\
        x_1 - 2x_2  &\leq 1\\
    x_1, x_2  &\geq 0
\end{align*}
      

In [102]:
import numpy as np

## Initial table 

In [103]:
cj = np.array([2, 1, 0, 0, 0, 0], dtype=float)

A = np.array([
    [1, 2, 1, 0, 0, 0], 
    [1, 1, 0, 1, 0, 0], 
    [1, -1, 0, 0, 1, 0], 
    [1, -2, 0, 0, 0, 1],
], 
    dtype=float)

b = np.array([10, 6, 2, 1], dtype=float)


solution_vector = np.zeros_like(cj)

inf_ratios = np.full(b.size, np.inf)  # []

num_rows, num_cols = A.shape

In [104]:
print(A, "\n")
print("where function\n", np.where(A == 1))
print(np.where(A == 1)[0])
print(np.where(A == 1)[1])

print()
print("Length of vector b:", b.size, "\n")


print("np.full( ) function")
print(np.full(b.size, np.inf))

[[ 1.  2.  1.  0.  0.  0.]
 [ 1.  1.  0.  1.  0.  0.]
 [ 1. -1.  0.  0.  1.  0.]
 [ 1. -2.  0.  0.  0.  1.]] 

where function
 (array([0, 0, 1, 1, 1, 2, 2, 3, 3]), array([0, 2, 0, 1, 3, 0, 4, 0, 5]))
[0 0 1 1 1 2 2 3 3]
[0 2 0 1 3 0 4 0 5]

Length of vector b: 4 

np.full( ) function
[inf inf inf inf]


In [105]:
numxvars = 2
onecols = np.where(A == 1)[1]
cb_index =  onecols[onecols >= numxvars] 
print(cb_index)

[2 3 4 5]


### Update $Z_j$ and $c_j - Z_j$

In [106]:
cb = cj[cb_index]
zj = cb.dot(A)
net_evaluation = cj - zj
print("Optimal solution") if np.all(net_evaluation <= 0) else print("Next Iteration")

Next Iteration


## Iteration 1

In [107]:
entering = net_evaluation.argmax()
key_col = A[:, entering] 
ratios = np.divide(b, key_col, out=inf_ratios, where=key_col>0)
leaving =  ratios.argmin()

pivot = A[leaving, entering]
print(pivot)

1.0


In [108]:
if pivot != 1:
    A[leaving] /= pivot
    b[leaving] /= pivot

### Gauss Jordan

In [109]:
for i in range(num_rows):
    if i == leaving: 
        continue
    factor = A[i, entering]
    A[i] += -factor * A[leaving] 
    b[i] += -factor * b[leaving] 
print(A)        
print(b)

[[ 0.  4.  1.  0.  0. -1.]
 [ 0.  3.  0.  1.  0. -1.]
 [ 0.  1.  0.  0.  1. -1.]
 [ 1. -2.  0.  0.  0.  1.]]
[9. 5. 1. 1.]


In [110]:
print(cb_index)
print(cb_index[leaving])
cb_index[leaving] = entering
print("After update: ", cb_index)

[2 3 4 5]
5
After update:  [2 3 4 0]


### Update $Z_j$ and $c_j - Z_j$

In [111]:
cb = cj[cb_index]
zj = cb.dot(A)
net_evaluation = cj - zj
solution_vector[~cb_index] = 0
solution_vector[cb_index] = b
print(cb)
print(zj)
print(net_evaluation)
print("Current Solution: ", solution_vector)
print("Optimal solution") if np.all(net_evaluation <= 0) else print("Next Iteration")

[0. 0. 0. 2.]
[ 2. -4.  0.  0.  0.  2.]
[ 0.  5.  0.  0.  0. -2.]
Current Solution:  [1. 0. 9. 5. 1. 0.]
Next Iteration


## Iteration 2

In [112]:
entering = net_evaluation.argmax()
key_col = A[:, entering] 
ratios = np.divide(b, key_col, out=inf_ratios, where=key_col>0)
leaving =  ratios.argmin()

pivot = A[leaving, entering]
print(pivot)

1.0


In [113]:
if pivot != 1:
    A[leaving] /= pivot
    b[leaving] /= pivot

### Gauss Jordan

In [114]:
for i in range(num_rows):
    if i == leaving: 
        continue
    factor = A[i, entering]
    A[i] += -factor * A[leaving] 
    b[i] += -factor * b[leaving] 
print(A)        
print(b)

[[ 0.  0.  1.  0. -4.  3.]
 [ 0.  0.  0.  1. -3.  2.]
 [ 0.  1.  0.  0.  1. -1.]
 [ 1.  0.  0.  0.  2. -1.]]
[5. 2. 1. 3.]


In [115]:
print(cb_index)
print(cb_index[leaving])
cb_index[leaving] = entering
print("After update: ", cb_index)

[2 3 4 0]
4
After update:  [2 3 1 0]


### Update $Z_j$ and $c_j - Z_j$

In [116]:
cb = cj[cb_index]
zj = cb.dot(A)
net_evaluation = cj - zj
solution_vector[~cb_index] = 0
solution_vector[cb_index] = b
print(cb)
print(zj)
print(net_evaluation)
print("Current Solution: ", solution_vector)
print("Optimal solution") if np.all(net_evaluation <= 0) else print("Next Iteration")

[0. 0. 1. 2.]
[ 2.  1.  0.  0.  5. -3.]
[ 0.  0.  0.  0. -5.  3.]
Current Solution:  [3. 1. 5. 2. 0. 0.]
Next Iteration


## Iteration 3

In [117]:
entering = net_evaluation.argmax()
key_col = A[:, entering] 
ratios = np.divide(b, key_col, out=inf_ratios, where=key_col>0)
leaving =  ratios.argmin()

pivot = A[leaving, entering]
print(pivot)

2.0


In [118]:
if pivot != 1:
    A[leaving] /= pivot
    b[leaving] /= pivot

### Gauss Jordan

In [119]:
for i in range(num_rows):
    if i == leaving: 
        continue
    factor = A[i, entering]
    A[i] += -factor * A[leaving] 
    b[i] += -factor * b[leaving] 
print(A)        
print(b)

[[ 0.   0.   1.  -1.5  0.5  0. ]
 [ 0.   0.   0.   0.5 -1.5  1. ]
 [ 0.   1.   0.   0.5 -0.5  0. ]
 [ 1.   0.   0.   0.5  0.5  0. ]]
[2. 1. 2. 4.]


In [120]:
print(cb_index)
print(cb_index[leaving])
cb_index[leaving] = entering
print("After update: ", cb_index)

[2 3 1 0]
3
After update:  [2 5 1 0]


### Update $Z_j$ and $c_j - Z_j$

In [121]:
cb = cj[cb_index]
zj = cb.dot(A)
net_evaluation = cj - zj
solution_vector[~cb_index] = 0
solution_vector[cb_index] = b
print(cb)
print(zj)
print(net_evaluation)
print("Current Solution: ", solution_vector)
print("Optimal solution") if np.all(net_evaluation <= 0) else print("Next Iteration")

[0. 0. 1. 2.]
[2.  1.  0.  1.5 0.5 0. ]
[ 0.   0.   0.  -1.5 -0.5  0. ]
Current Solution:  [4. 2. 2. 0. 0. 1.]
Optimal solution
