In [1]:
import numpy as np

In [3]:
cj = np.array([2, 1, 0, 0, 0, 0], dtype=float)

A = np.array([
    [1, 2, 1, 0, 0, 0], 
    [1, 1, 0, 1, 0, 0], 
    [1, -1, 0, 0, 1, 0], 
    [1, -2, 0, 0, 0, 1],
], 
    dtype=float)

b = np.array([10, 6, 2, 1], dtype=float)

In [4]:
%run "simplex_algorithm.ipynb"

In [5]:
sols, zvalues = simplex(matrix=A, rhs=b, z=cj, numxvars=2, direction=1)

Iteration 1
[[ 0.  4.  1.  0.  0. -1.]
 [ 0.  3.  0.  1.  0. -1.]
 [ 0.  1.  0.  0.  1. -1.]
 [ 1. -2.  0.  0.  0.  1.]] 

Solution [1. 0. 9. 5. 1. 0.] 	Z: 2.00 

Iteration 2
[[ 0.  0.  1.  0. -4.  3.]
 [ 0.  0.  0.  1. -3.  2.]
 [ 0.  1.  0.  0.  1. -1.]
 [ 1.  0.  0.  0.  2. -1.]] 

Solution [3. 1. 5. 2. 0. 0.] 	Z: 7.00 

Iteration 3
[[ 0.   0.   1.  -1.5  0.5  0. ]
 [ 0.   0.   0.   0.5 -1.5  1. ]
 [ 0.   1.   0.   0.5 -0.5  0. ]
 [ 1.   0.   0.   0.5  0.5  0. ]] 

Solution [4. 2. 2. 0. 0. 1.] 	Z: 10.00 

Optimal solution found in 3 iterations
