In [2]:
import numpy as np

In [62]:
def simplex(matrix, rhs, z, numxvars, direction=1):
    '''Simplex algorithm to solve linear programming problems
    
    Parameters
    ----------
    matrix: numpy ndarray
        Matrix of coefficients in the left-hand side
    
    rhs: numpy ndarray
        Right-hand side vector
    
    numxvars: int
        Number of x variables
        
    direction: {+1 , -1}
        For maximization problems use +1 and for minimization problems use -1 instead.
    '''
    infinity_ratios = np.full(rhs.size, np.inf)  # infinity
    solution = np.zeros_like(z)
    num_rows, num_cols = matrix.shape
    
    onecols = np.where(matrix == 1)[1]
    cb_index = onecols[onecols >= numxvars]
    
    iteration = 0
    
    cb = z[cb_index]
    
    zj = cb.dot(matrix)
    net_evaluation = direction * (z - zj)

    while np.any(net_evaluation > 0):
        entering = net_evaluation.argmax()  # entering variables (index)
        
        key_col = matrix[ : , entering]
        ratios = np.divide(rhs, key_col, out=infinity_ratios, where=key_col>0)
        leaving = ratios.argmin()   # leaving variables (index)
        
        pivot = matrix[leaving, entering]
        
        if pivot != 1:
            matrix[leaving] = matrix[leaving] / pivot
            rhs[leaving] = rhs[leaving] / pivot
        
        for i in range(num_rows):
            if i == leaving:
                continue
            factor = matrix[i, entering]
            matrix[i] = -factor * matrix[leaving] + matrix[i]
            rhs[i] = -factor * rhs[leaving] + rhs[i]
        
        cb_index[leaving] = entering
        
        cb = cj[cb_index]
        zj = cb.dot(matrix)
        net_evaluation = direction * (z - zj)

        solution[~cb_index] = 0  # non-basics
        solution[cb_index] = rhs  # basics
        
        print(matrix, "\n")
        print("Solution", solution, "\n")
        
        iteration += 1
        
        if np.all(net_evaluation <= 0):
            print(f"Optimal solution found in {iteration} iterations with solution {solution}" )

In [63]:
cj = np.array( [2,1,0,0,0,0]  ,  dtype=float)

A = np.array( [
    [1,  2, 1,0,0,0],  # 0
    [1,  1, 0,1,0,0],  # 1
    [1, -1, 0,0,1,0],
    [1, -2, 0,0,0,1],
] , dtype=float)

b = np.array( [10, 6, 2, 1] , dtype=float )

In [64]:
simplex(matrix=A, rhs=b, z=cj, numxvars=2, direction=1)

[[ 0.  4.  1.  0.  0. -1.]
 [ 0.  3.  0.  1.  0. -1.]
 [ 0.  1.  0.  0.  1. -1.]
 [ 1. -2.  0.  0.  0.  1.]] 

Solution [1. 0. 9. 5. 1. 0.] 

[[ 0.  0.  1.  0. -4.  3.]
 [ 0.  0.  0.  1. -3.  2.]
 [ 0.  1.  0.  0.  1. -1.]
 [ 1.  0.  0.  0.  2. -1.]] 

Solution [3. 1. 5. 2. 0. 0.] 

[[ 0.   0.   1.  -1.5  0.5  0. ]
 [ 0.   0.   0.   0.5 -1.5  1. ]
 [ 0.   1.   0.   0.5 -0.5  0. ]
 [ 1.   0.   0.   0.5  0.5  0. ]] 

Solution [4. 2. 2. 0. 0. 1.] 

Optimal solution found in 3 iterations with solution [4. 2. 2. 0. 0. 1.]


In [66]:
cj = np.array( [12, 20, 0, 0, 1000, 1000]  ,  dtype=float)

A = np.array( [
    [6,  8, -1,  0, 1, 0],  # 0
    [7, 12,  0, -1, 0, 1],  # 1
] , dtype=float)

b = np.array( [100, 120] , dtype=float )

In [67]:
simplex(matrix=A, rhs=b, z=cj, numxvars=2, direction=-1)

[[ 1.33333333  0.         -1.          0.66666667  1.         -0.66666667]
 [ 0.58333333  1.          0.         -0.08333333  0.          0.08333333]] 

Solution [ 0. 10.  0.  0. 20.  0.] 

[[ 1.      0.     -0.75    0.5     0.75   -0.5   ]
 [ 0.      1.      0.4375 -0.375  -0.4375  0.375 ]] 

Solution [15.    1.25  0.    0.    0.    0.  ] 

Optimal solution found in 2 iterations with solution [15.    1.25  0.    0.    0.    0.  ]
