# Example 04-11

$$\max Z = 40x_1 + 25x_2 + 50x_3$$

\begin{align*}
x_1 + 2x_2 + x_3 &\leq 36 \\
2x_1 + x_2 + 4x_3 &\leq 60 \\
2x_1 + 5x_2 + x_3 &\leq 45 \\[5mm]
x_1, x_2, x_3 &\geq 0
\end{align*}

In [35]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

In [36]:
%run "../auxfunc/fullmatrix.ipynb"
%run "../auxfunc/algorithms.ipynb"

In [37]:
cj = [40, 25, 50]

A = np.array([
    [1, 2, 1],
    [2, 1, 4],
    [2, 5, 1],
])

b = [36, 60, 45]

ineq = ["<="] * 3


In [38]:
solprimal, zvalues, lastprimalrow = simplex(matrix=A, rhs=b, z=cj, inequalities=ineq)

Iteration 1. Entering: x3, Leaving: Leaving: s2
[[ 0.5   1.75  0.    1.   -0.25  0.  ]
 [ 0.5   0.25  1.    0.    0.25  0.  ]
 [ 1.5   4.75  0.    0.   -0.25  1.  ]] 

Solution [ 0.  0. 15. 21.  0. 30.] 	Z: 750.00 

Iteration 2. Entering: x1, Leaving: Leaving: s3
[[ 0.     0.167  0.     1.    -0.167 -0.333]
 [ 0.    -1.333  1.     0.     0.333 -0.333]
 [ 1.     3.167  0.     0.    -0.167  0.667]] 

Solution [20.  0.  5. 11.  0.  0.] 	Z: 1050.00 

Optimal solution found in 2 iterations
('x1', 20.0) ('x2', 0.0) ('x3', 5.0) ('s1', 11.0) ('s2', 0.0) ('s3', 0.0)


In [39]:
solprimal

array([[ 0.,  0., 15., 21.,  0., 30.],
       [20.,  0.,  5., 11.,  0.,  0.]])

In [40]:
print(zvalues)

[750.0, 1050.0]


In [41]:
print(lastprimalrow)

[[ 40.  60.  50.   0.  10.  10.]
 [  0. -35.   0.   0. -10. -10.]]


In [42]:
cjdual = b
Adual = A.T

bdual = cj

ineqdual = [">="] * 3

In [43]:
soldual, wvalues, lastdualrow = simplex(matrix=Adual, rhs=bdual, z=cjdual, inequalities=ineqdual, direction=-1, vlabel="y")

Iteration 1. Entering: y3, Leaving: Leaving: A2
[[ 0.2  1.6  0.  -1.   1.   0.4 -0.4  0.   0. ]
 [ 0.4  0.2  1.   0.   0.  -0.2  0.2  0.   0. ]
 [ 0.6  3.8  0.   0.   0.   0.2 -0.2 -1.   1. ]] 

Solution [ 0.  0.  5.  0. 30.  0.  0.  0. 45.] 	Z: 75225.00 

Iteration 2. Entering: y2, Leaving: Leaving: A3
[[-0.053  0.     0.    -1.     1.     0.316 -0.316  0.421 -0.421]
 [ 0.368  0.     1.     0.     0.    -0.211  0.211  0.053 -0.053]
 [ 0.158  1.     0.     0.     0.     0.053 -0.053 -0.263  0.263]] 

Solution [ 0.    11.842  2.632  0.    11.053  0.     0.     0.     0.   ] 	Z: 11881.58 

Iteration 3. Entering: s3, Leaving: Leaving: A1
[[-0.125  0.     0.    -2.375  2.375  0.75  -0.75   1.    -1.   ]
 [ 0.375  0.     1.     0.125 -0.125 -0.25   0.25   0.     0.   ]
 [ 0.125  1.     0.    -0.625  0.625  0.25  -0.25   0.     0.   ]] 

Solution [ 0.   18.75  1.25  0.    0.    0.    0.   26.25  0.  ] 	Z: 1181.25 

Iteration 4. Entering: s2, Leaving: Leaving: s3
[[-0.167  0.     0.    -3.167

In [44]:
print(soldual)

[[ 0.     0.     5.     0.    30.     0.     0.     0.    45.   ]
 [ 0.    11.842  2.632  0.    11.053  0.     0.     0.     0.   ]
 [ 0.    18.75   1.25   0.     0.     0.     0.    26.25   0.   ]
 [ 0.    10.    10.     0.     0.    35.     0.     0.     0.   ]]


In [45]:
print(wvalues)

[75225.0, 11881.578947368418, 1181.25, 1050.0]


In [46]:
print(lastdualrow)

[[   25.    60.    45.   -20.    20.     0.     0.    -5.     5.]
 [  -11.    -0.    -0.   -20.  -980.    -0. -1000.    -5.  -995.]]
