# Example Economic Interpretation

$$\min Z = 600x_1 + 400x_2$$

\begin{align*}
1500x_1 + 1500x_2 &\geq 20000 \\
3000x_1 + 1000x_2 &\geq 40000 \\
2000x_1 + 5000x_2 &\geq 44000 \\[5mm]
x_1, x_2 &\geq 0
\end{align*}

In [16]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

In [17]:
%run "../auxfunc/fullmatrix.ipynb"
%run "../auxfunc/algorithms.ipynb"

In [18]:
cjprimal = [600, 400]

Aprimal = np.array([
    [1500, 1500],
    [3000, 1000],
    [2000, 5000],
])

bprimal = [20000, 40000, 44000]

ineqprimal = [">="] * 3


In [19]:
solprimal, zvalues, lastprimalrow = simplex(matrix=Aprimal, rhs=bprimal, z=cjprimal, inequalities=ineqprimal, direction=-1)

Iteration 1. Entering: x2, Leaving: Leaving: A3
[[ 900.     0.    -1.     1.     0.     0.     0.3   -0.3]
 [2600.     0.     0.     0.    -1.     1.     0.2   -0.2]
 [   0.4    1.     0.     0.     0.     0.    -0.     0. ]] 

Solution [    0.      8.8     0.   6800.      0.  31200.      0.      0. ] 	Z: 38003520.00 

Iteration 2. Entering: x1, Leaving: Leaving: A1
[[ 1.    0.   -0.    0.    0.    0.    0.   -0.  ]
 [ 0.    0.    2.89 -2.89 -1.    1.   -0.67  0.67]
 [ 0.    1.    0.   -0.    0.    0.   -0.    0.  ]] 

Solution [    7.56     5.78     0.       0.       0.   11555.56     0.       0.  ] 	Z: 11562400.00 

Iteration 3. Entering: s1, Leaving: Leaving: A2
[[ 1.    0.    0.    0.   -0.    0.    0.   -0.  ]
 [ 0.    0.    1.   -1.   -0.35  0.35 -0.23  0.23]
 [ 0.    1.    0.    0.    0.   -0.   -0.    0.  ]] 

Solution [  12.    4. 4000.    0.    0.    0.    0.    0.] 	Z: 8800.00 

Optimal solution found in 3 iterations
('x1', 12.0) ('x2', 4.0) ('s1', 4000.0) ('A1', 0.0) ('s2',

In [28]:
print(solprimal)

[[    0.       8.8      0.    6800.       0.   31200.       0.       0.  ]
 [    7.56     5.78     0.       0.       0.   11555.56     0.       0.  ]
 [   12.       4.    4000.       0.       0.       0.       0.       0.  ]]


In [21]:
print(zvalues)

[38003520.0, 11562400.000000007, 8800.0]


In [22]:
print(lastprimalrow)

[[  600.     400.       0.       0.      -0.17     0.17    -0.05     0.05]
 [   -0.      -0.      -0.   -1000.      -0.17  -999.83    -0.05  -999.95]]


In [23]:
cjdual = bprimal
Adual = Aprimal.T

bdual = cjprimal

ineqdual = ["<="] * 2

In [24]:
soldual, wvalues, lastdualrow = simplex(matrix=Adual, rhs=bdual, z=cjdual, inequalities=ineqdual, direction=1, vlabel="y")

Iteration 1. Entering: y3, Leaving: Leaving: s2
[[ 900.  2600.     0.     1.    -0.4]
 [   0.3    0.2    1.     0.     0. ]] 

Solution [  0.     0.     0.08 440.     0.  ] 	Z: 3520.00 

Iteration 2. Entering: y2, Leaving: Leaving: s1
[[ 0.35  1.    0.    0.   -0.  ]
 [ 0.23  0.    1.   -0.    0.  ]] 

Solution [0.   0.17 0.05 0.   0.  ] 	Z: 8800.00 

Optimal solution found in 2 iterations
('y1', 0.0) ('y2', 0.169) ('y3', 0.046) ('s1', 0.0) ('s2', 0.0)


In [25]:
print(soldual)

[[  0.     0.     0.08 440.     0.  ]
 [  0.     0.17   0.05   0.     0.  ]]


In [26]:
print(wvalues)

[3520.0, 8800.0]


In [27]:
print(lastdualrow)

[[24000. 40000. 44000.    12.     4.]
 [-4000.     0.     0.   -12.    -4.]]
