# Example 04-10

In [3]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

In [2]:
%run "algorithms.ipynb"

In [8]:
S = np.diag([-1,-1,-1,-1])
A = np.eye(4)

c = np.array([0.07, 0.05])
cj = np.concatenate((c, np.zeros() ))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
