# Activity 5.4

## Exercise 01

$$ \max Z = 3x_1 + 2x_2  + 5x_3$$

  \begin{align*}
    x_1 + 2x_2  + x_3 &\leq 430\\[3mm]
3x_1 + 2x_3  &\leq 460\\[3mm]
    x_1 + 4x_2   &\leq 420\\[3mm]
    x_1, x_2, x_3 &\geq 0
  \end{align*}

In [2]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [3]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [6]:
cj1 = [3, 2, 5]

A1 = np.array([
    [1, 2, 1],
    [3, 0, 2],
    [1, 4, 0],
])

b1 = [430, 460, 420]

ineq1 = ["<=", "<=", "<="]

In [7]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1)

==================== Simplex Method ====================
####################
Iteration 1. s2 --> x3
--------------------
[[-0.5  2.   0.   1.  -0.5  0. ]
 [ 1.5  0.   1.   0.   0.5  0. ]
 [ 1.   4.   0.   0.   0.   1. ]] 

    Basis
s1    0.0
x3    5.0
s3    0.0
Solution [  0.   0. 230. 200.   0. 420.] 	Z: 1150.00 

####################
Iteration 2. s1 --> x2
--------------------
[[-0.25  1.    0.    0.5  -0.25  0.  ]
 [ 1.5   0.    1.    0.    0.5   0.  ]
 [ 2.    0.    0.   -2.    1.    1.  ]] 

    Basis
x2    2.0
x3    5.0
s3    0.0
Solution [  0. 100. 230.   0.   0.  20.] 	Z: 1350.00 

####################
Optimal solution found in 2 iterations
    Solution
x1       0.0
x2     100.0
x3     230.0
s1       0.0
s2       0.0
s3      20.0

Optimal Table:
     Cb    x1   x2   x3   s1    s2   s3      b
x2  2.0 -0.25  1.0  0.0  0.5 -0.25  0.0  100.0
x3  5.0  1.50  0.0  1.0  0.0  0.50  0.0  230.0
s3  0.0  2.00  0.0  0.0 -2.0  1.00  1.0   20.0

Row Base:
          x1   x2   x3   s1   s2   

## Exercise 02

$$ \max Z = 20x_1 + 10x_2 $$

  \begin{align*}
    x_1 + 2x_2   &\leq 40\\[3mm]
3x_1 + 2x_2  &\leq 60\\[3mm]
    x_1, x_2 &\geq 0
  \end{align*}
  
  Find the optimal solution. Also determine the optimal solution if $x_2$-column changes from
$
\begin{bmatrix}
  2\\
  2\\
\end{bmatrix}
$
to 
$
\begin{bmatrix}
  2\\
  1\\
\end{bmatrix}
$

In [14]:
cj2 = [20, 10]

A2 = np.array([
    [1, 2],
    [3, 1],
])

b2 = [40, 60]

ineq2 = ["<=", "<="]

In [15]:
sol2, z2, lastrow12, optitable12 = simplex(matrix=A2,
                                        rhs=b2, 
                                        z=cj2, 
                                        inequalities=ineq2)

==================== Simplex Method ====================
####################
Iteration 1. s2 --> x1
--------------------
[[ 0.     1.667  1.    -0.333]
 [ 1.     0.333  0.     0.333]] 

    Basis
s1    0.0
x1   20.0
Solution [20.  0. 20.  0.] 	Z: 400.00 

####################
Iteration 2. s1 --> x2
--------------------
[[ 0.   1.   0.6 -0.2]
 [ 1.   0.  -0.2  0.4]] 

    Basis
x2   10.0
x1   20.0
Solution [16. 12.  0.  0.] 	Z: 440.00 

####################
Optimal solution found in 2 iterations
    Solution
x1      16.0
x2      12.0
s1       0.0
s2       0.0

Optimal Table:
      Cb   x1   x2   s1   s2     b
x2  10.0  0.0  1.0  0.6 -0.2  12.0
x1  20.0  1.0  0.0 -0.2  0.4  16.0

Row Base:
           x1    x2   s1   s2
zj       20.0  10.0  2.0  6.0
cj - zj   0.0   0.0 -2.0 -6.0
