# Activity 5.3

  $$ \max Z = 20x_1 + 15x_2 $$

  \begin{align*}
    \frac{x_1}{500} + \frac{x_2}{700}   &\leq 1\\[3mm]
\frac{x_1}{650} + \frac{x_2}{330}  &\leq 1\\[3mm]
    \frac{x_1}{450} + \frac{x_2}{700}   &\leq 1\\[3mm]
    x_1, x_2 &\geq 0
  \end{align*}

In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [2]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [7]:
cj1 = [20, 15]

A1 = np.array([
    [1/500, 1/700],
    [1/650, 1/330],
    [1/450, 1/700],
])

b1 = [1, 1, 1]

ineq1 = ["<=", "<=", "<="]

In [8]:
cj2 = [20, 15, 16]

A2 = np.array([
    [1/500, 1/700, 1/200],
    [1/650, 1/330, 1/180],
    [1/450, 1/700, 1/120],
])

b2 = [1, 1, 1]

ineq2 = ["<=", "<=", "<="]

In [10]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1)

==================== Simplex Method ====================
####################
Iteration 1. s3 --> x1
--------------------
[[  0.      0.      1.      0.     -0.9  ]
 [  0.      0.002   0.      1.     -0.692]
 [  1.      0.643   0.      0.    450.   ]] 

    Basis
s1    0.0
s2    0.0
x1   20.0
Solution [450.      0.      0.1     0.308   0.   ] 	Z: 9000.00 

####################
Iteration 2. s2 --> x2
--------------------
[[   0.       0.       1.      -0.07    -0.852]
 [   0.       1.       0.     489.886 -339.152]
 [   1.       0.       0.    -314.927  668.026]] 

    Basis
s1    0.0
x2   15.0
x1   20.0
Solution [353.1   150.734   0.078   0.      0.   ] 	Z: 9323.00 

####################
Optimal solution found in 2 iterations
      Solution
x1  353.099511
x2  150.734095
s1    0.078467
s2    0.000000
s3    0.000000

Optimal Table:
      Cb   x1   x2   s1          s2          s3           b
s1   0.0  0.0  0.0  1.0   -0.069984   -0.851550    0.078467
x2  15.0  0.0  1.0  0.0  489.885808 -3

In [9]:
sol2, z2, lastrow12, optitable12 = simplex(matrix=A2,
                                        rhs=b2, 
                                        z=cj2, 
                                        inequalities=ineq2)

==================== Simplex Method ====================
####################
Iteration 1. s3 --> x1
--------------------
[[  0.      0.     -0.002   1.      0.     -0.9  ]
 [  0.      0.002  -0.      0.      1.     -0.692]
 [  1.      0.643   3.75    0.      0.    450.   ]] 

    Basis
s1    0.0
s2    0.0
x1   20.0
Solution [450.      0.      0.      0.1     0.308   0.   ] 	Z: 9000.00 

####################
Iteration 2. s2 --> x2
--------------------
[[   0.       0.      -0.002    1.      -0.07    -0.852]
 [   0.       1.      -0.105    0.     489.886 -339.152]
 [   1.       0.       3.817    0.    -314.927  668.026]] 

    Basis
s1    0.0
x2   15.0
x1   20.0
Solution [353.1   150.734   0.      0.078   0.      0.   ] 	Z: 9323.00 

####################
Optimal solution found in 2 iterations
      Solution
x1  353.099511
x2  150.734095
x3    0.000000
s1    0.078467
s2    0.000000
s3    0.000000

Optimal Table:
      Cb   x1   x2        x3   s1          s2          s3           b
s1   0