# Activity 5.2

$$\max Z = 3x_1 + 3x_2 + 4x_3 + 7x_4 $$
  \begin{align*}
  x_1 + x_2 + x_3 + x_4  & \leq 9\\
5x_1 + 3x_2 + 2x_3 + x_4  &\leq 60\\
x_1 + 3x_2 + 5x_3 + 8x_4  &\leq 50\\
    x_1, x_2 &\geq 0\\
  \end{align*}

In [2]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [3]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [4]:
cj1 = [3, 3, 4, 7]

A1 = np.array([
    [1, 1, 1, 1],
    [5, 3, 2, 1],
    [1, 3, 5, 8],
])

b1 = [9, 60, 50]

ineq1 = ["<=", "<=", "<="]

In [7]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1)

==================== Simplex Method ====================
####################
Iteration 1. s3 --> x4
--------------------
[[ 0.875  0.625  0.375  0.     1.     0.    -0.125]
 [ 4.875  2.625  1.375  0.     0.     1.    -0.125]
 [ 0.125  0.375  0.625  1.     0.     0.     0.125]] 

    Basis
s1    0.0
s2    0.0
x4    7.0
Solution [ 0.    0.    0.    6.25  2.75 53.75  0.  ] 	Z: 43.75 

####################
Iteration 2. s1 --> x1
--------------------
[[ 1.     0.714  0.429  0.     1.143  0.    -0.143]
 [ 0.    -0.857 -0.714  0.    -5.571  1.     0.571]
 [ 0.     0.286  0.571  1.    -0.143  0.     0.143]] 

    Basis
x1    3.0
s2    0.0
x4    7.0
Solution [ 3.143  0.     0.     5.857  0.    38.429  0.   ] 	Z: 50.43 

####################
Optimal solution found in 2 iterations
     Solution
x1   3.142857
x2   0.000000
x3   0.000000
x4   5.857143
s1   0.000000
s2  38.428571
s3   0.000000

Optimal Table:
     Cb   x1        x2        x3   x4        s1   s2        s3          b
x1  3.0  1.0  0.