# Example 01

$$\max Z = 5x_1 + 12x_2 + 4x_3 $$

\begin{align*}
x_1 + 2x_2 + x_3 &\leq 5\\
2x_1 - x_2 +3x_3 &= 2\\[5mm]  
x_1 , x_2, x_3 &\geq 0
\end{align*}

In [244]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [261]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [249]:
cj = [5, 12, 4]

A = np.array([
    [1, 2, 1],
    [2, -1, 3],
    [-2, 1, -3],
])

b = [5, 2, -2]

ineq = ["<=", "<=", "<="]

In [262]:
solprimal, zvalues, lastprimalrow, tableprimal = simplex(matrix=A, rhs=b, z=cj, inequalities=ineq)

[[ 1.  2.  1.  1.  0.  0.]
 [ 2. -1.  3.  0.  1.  0.]
 [-2.  1. -3.  0.  0.  1.]]
[3 4 5]
[0. 0. 0.]
Iteration 1. s3 --> x2
[[ 5.  0.  7.  1.  0. -2.]
 [ 0.  0.  0.  0.  1.  1.]
 [-2.  1. -3.  0.  0.  1.]] 

Solution [ 0. -2.  0.  9.  0.  0.] 	Z: -24.00 

Iteration 2. s1 --> x3
[[ 0.714  0.     1.     0.143  0.    -0.286]
 [ 0.     0.     0.     0.     1.     1.   ]
 [ 0.143  1.     0.     0.429  0.     0.143]] 

Solution [0.    1.857 1.286 0.    0.    0.   ] 	Z: 27.43 

Iteration 3. x3 --> x1
[[ 1.   0.   1.4  0.2  0.  -0.4]
 [ 0.   0.   0.   0.   1.   1. ]
 [ 0.   1.  -0.2  0.4  0.   0.2]] 

Solution [1.8 1.6 0.  0.  0.  0. ] 	Z: 28.20 

Optimal solution found in 3 iterations
('x1', 1.8) ('x2', 1.6) ('x3', 0.0) ('s1', 0.0) ('s2', 0.0) ('s3', 0.0)


In [ ]:
print(lastprimalrow)

In [ ]:
print(tableprimal)

In [ ]:
B = A[:2, :2]
Binv = np.linalg.inv(B)
print(B)
print(Binv)

In [ ]:
b2 = np.array([7, 2])
b3 = np.array([3, 9])

In [ ]:
print(Binv.dot(b2))
print(Binv.dot(b3))

In [263]:
cjdual = b

Adual = A.T

bdual = cj

ineqdual = [">=", ">=", ">="]

In [264]:
soldual, wvalues, lastdualrow, tabledual = simplex(matrix=Adual, rhs=bdual, z=cjdual, inequalities=ineqdual, direction=-1, vlabel="y")

[[ 1.  2. -2. -1.  1.  0.  0.  0.  0.]
 [ 2. -1.  1.  0.  0. -1.  1.  0.  0.]
 [ 1.  3. -3.  0.  0.  0.  0. -1.  1.]]
[4 6 8]
[1000. 1000. 1000.]
Iteration 1. A3 --> y2
[[ 0.333  0.     0.    -1.     1.     0.     0.     0.667 -0.667]
 [ 2.333  0.     0.     0.     0.    -1.     1.    -0.333  0.333]
 [ 0.333  1.    -1.     0.     0.     0.     0.    -0.333  0.333]] 

Solution [ 0.     1.333  0.     0.     2.333  0.    13.333  0.     0.   ] 	Z: 15669.33 

Iteration 2. y2 --> y1
[[ 0. -1.  1. -1.  1.  0.  0.  1. -1.]
 [ 0. -7.  7.  0.  0. -1.  1.  2. -2.]
 [ 1.  3. -3.  0.  0.  0.  0. -1.  1.]] 

Solution [4. 0. 0. 0. 1. 0. 4. 0. 0.] 	Z: 5020.00 

Iteration 3. A2 --> y3
[[ 0.     0.     0.    -1.     1.     0.143 -0.143  0.714 -0.714]
 [ 0.    -1.     1.     0.     0.    -0.143  0.143  0.286 -0.286]
 [ 1.     0.     0.     0.     0.    -0.429  0.429 -0.143  0.143]] 

Solution [5.714 0.    0.571 0.    0.429 0.    0.    0.    0.   ] 	Z: 456.00 

Iteration 4. A1 --> s3
[[ 0.   0.   0.  -1.4

In [258]:
print(lastdualrow)

[[    5.      2.     -2.     -1.8     1.8    -1.6     1.6     0.      0. ]
 [   -0.     -0.     -0.     -1.8  -998.2    -1.6  -998.4    -0.  -1000. ]]
