# Sensitivity Analysis Exam 02-01

## Exercise 01

Solve the problem

$$ \min Z = -x_1 + 2x_2 + 3x_3$$

  \begin{align*}
    -x_1 + x_2 +x_3\geq 3,\\
    x_1 + 2x_2 + x_3 \leq 10\\[3mm]
    x_1, x_2, x_3 &\geq 0
  \end{align*}
  
Si los coeficientes tecnológicos de $x_1$ cambian de $
\begin{bmatrix}
  -1\\
   1
\end{bmatrix}
$ a
$\begin{bmatrix}
  2\\
  1
\end{bmatrix}$, encuentre la nueva solución óptima.
  


In [13]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [14]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [15]:
cj1 = [-1, 2, 3]

A1 = np.array([
    [-1, 1, 1],
    [1, 2, 1],
])

b1 = [3, 10]

ineq1 = [">=", "<="]

In [16]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1,
                                           direction=-1,
                                        vlabel="x")

==================== Simplex Method ====================
####################
Iteration 1. A1 --> x2
--------------------
[[-1.  1.  1. -1.  1.  0.]
 [ 3.  0. -1.  2. -2.  1.]] 

    Basis
x2    2.0
s2    0.0
Solution [0. 3. 0. 0. 0. 4.] 	Z: 6.00 

####################
Optimal solution found in 1 iterations
    Solution
x1       0.0
x2       3.0
x3       0.0
s1       0.0
A1       0.0
s2       4.0

Optimal Table:
     Cb   x1   x2   x3   s1   A1   s2    b
x2  2.0 -1.0  1.0  1.0 -1.0  1.0  0.0  3.0
s2  0.0  3.0  0.0 -1.0  2.0 -2.0  1.0  4.0

Row Base:
          x1   x2   x3   s1     A1   s2
zj      -2.0  2.0  2.0 -2.0    2.0  0.0
cj - zj  1.0  0.0  1.0  2.0  998.0  0.0


## Exercise 02

Una fábrica de muebles fabrica $x_1$ sillas, $x_2$ mesas y $x_3$ aparadores. Se ha formulado el siguiente modelo de producción:

$$ \max Z = 20x_1 + 15x_2 + 15x_3$$

  \begin{align*}
    8x_1 + 2x_2 + 8x_3 &\leq 100\\
    4x_1 + 4x_2 + 4x_3 &\leq 60\\[3mm]
    x_1, x_2, x_3 & \geq 0
  \end{align*}
  
1. Escribir el problema en su forma dual,
2. Resolver el problema dual.
3. Determinar los rangos de los lados derecho.
4. Determinar los rangos de las contribuciones de $x_1, x_2, x_3$ para que la solución sigua siendo óptima.

## Dual Problem Formulation

$$\min 100y_1 + 60y_2$$

\begin{align*}
    8y_1 + 4y_2 &\geq 20\\
    2y_1 + 4y_2 &\geq 15\\
    8y_1 + 4y_2 & \geq 15\\[3mm]
    y_1, y_2 & \geq 0
  \end{align*}

In [17]:
cj2 = [100, 60]

A2 = np.array([
    [8, 4],
    [2, 4],
    [8, 4],
])

b2 = [20, 15, 15]

ineq2 = [">="] * 3 

In [18]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A2,
                                        rhs=b2, 
                                        z=cj2, 
                                        inequalities=ineq2,
                                           direction=-1,
                                        vlabel="y")

==================== Simplex Method ====================
####################
Iteration 1. A3 --> y1
--------------------
[[ 0.     0.    -1.     1.     0.     0.     1.    -1.   ]
 [ 0.     3.     0.     0.    -1.     1.     0.25  -0.25 ]
 [ 1.     0.5    0.     0.     0.     0.    -0.125  0.125]] 

     Basis
A1  1000.0
A2  1000.0
y1   100.0
Solution [ 1.875  0.     0.     5.     0.    11.25   0.     0.   ] 	Z: 16437.50 

####################
Iteration 2. A2 --> y2
--------------------
[[ 0.     0.    -1.     1.     0.     0.     1.    -1.   ]
 [ 0.     1.     0.     0.    -0.333  0.333  0.083 -0.083]
 [ 1.     0.     0.     0.     0.167 -0.167 -0.167  0.167]] 

     Basis
A1  1000.0
y2    60.0
y1   100.0
Solution [0.   3.75 0.   5.   0.   0.   0.   0.  ] 	Z: 5225.00 

####################
Iteration 3. A1 --> s3
--------------------
[[ 0.     0.    -1.     1.     0.     0.     1.    -1.   ]
 [ 0.     1.     0.083 -0.083 -0.333  0.333  0.     0.   ]
 [ 1.     0.    -0.167  0.167  0.16

### Solving The Primal

In [19]:
cj3 = [20, 15, 15]

A3 = np.array([
    [8, 2, 8],
    [4, 4, 4],
])

b3 = [100, 60]

ineq3 = ["<="] * 2 

In [20]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A3,
                                        rhs=b3, 
                                        z=cj3, 
                                        inequalities=ineq3,
                                        direction=1,
                                        vlabel="x")

==================== Simplex Method ====================
####################
Iteration 1. s1 --> x1
--------------------
[[ 1.     0.25   1.     0.125  0.   ]
 [ 0.     3.     0.    -0.5    1.   ]] 

    Basis
x1   20.0
s2    0.0
Solution [12.5  0.   0.   0.  10. ] 	Z: 250.00 

####################
Iteration 2. s2 --> x2
--------------------
[[ 1.     0.     1.     0.167 -0.083]
 [ 0.     1.     0.    -0.167  0.333]] 

    Basis
x1   20.0
x2   15.0
Solution [11.667  3.333  0.     0.     0.   ] 	Z: 283.33 

####################
Optimal solution found in 2 iterations
     Solution
x1  11.666667
x2   3.333333
x3   0.000000
s1   0.000000
s2   0.000000

Optimal Table:
      Cb   x1   x2   x3        s1        s2          b
x1  20.0  1.0  0.0  1.0  0.166667 -0.083333  11.666667
x2  15.0  0.0  1.0  0.0 -0.166667  0.333333   3.333333

Row Base:
           x1    x2    x3        s1        s2
zj       20.0  15.0  20.0  0.833333  3.333333
cj - zj   0.0   0.0  -5.0 -0.833333 -3.333333
