# Example 05

$$\max Z = 3x_1 + 5x_2 + 4x_3 $$

\begin{align*}
2x_1 + 3x_2 &\leq 8\\
 2x_2 + 5x_3 &\leq 10\\
3x_1 + 2x_2 + 4x_3& \leq 15\\[5mm]  
x_1 , x_2, x_3 &\geq 0
\end{align*}

In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [2]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [3]:
cj1 = [3, 5, 4]

A1 = np.array([
    [2, 3, 0],
    [0, 2, 5],
    [3, 2, 4],
])

b1 = [8, 10, 15]

ineq1 = ["<=", "<=", "<="]

In [4]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1)

==================== Simplex Method ====================
####################
Iteration 1. s1 --> x2
--------------------
[[ 0.667  1.     0.     0.333  0.     0.   ]
 [-1.333  0.     5.    -0.667  1.     0.   ]
 [ 1.667  0.     4.    -0.667  0.     1.   ]] 

    Basis
x2    5.0
s2    0.0
s3    0.0
Solution [0.    2.667 0.    0.    4.667 9.667] 	Z: 13.33 

####################
Iteration 2. s2 --> x3
--------------------
[[ 0.667  1.     0.     0.333  0.     0.   ]
 [-0.267  0.     1.    -0.133  0.2    0.   ]
 [ 2.733  0.     0.    -0.133 -0.8    1.   ]] 

    Basis
x2    5.0
x3    4.0
s3    0.0
Solution [0.    2.667 0.933 0.    0.    5.933] 	Z: 17.07 

####################
Iteration 3. s3 --> x1
--------------------
[[ 0.     1.     0.     0.366  0.195 -0.244]
 [ 0.     0.     1.    -0.146  0.122  0.098]
 [ 1.     0.     0.    -0.049 -0.293  0.366]] 

    Basis
x2    5.0
x3    4.0
x1    3.0
Solution [2.171 1.22  1.512 0.    0.    0.   ] 	Z: 18.66 

####################
Optimal solution