# Example 07

$$\max Z = 45x_1 + 100x_2 + 30x_3 + 50x_4 $$

\begin{align*}
7x_1 + 10x_2 + 4x_3 + 9x_4 &\leq 1200\\
3x_1 + 40x_2 + x_3 + x_4 &\leq 800\\\\[5mm]  
x_1 , x_2, x_3, x_4 &\geq 0
\end{align*}

In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [2]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [3]:
cj1 = [45, 100, 30, 50]

A1 = np.array([
    [7, 10, 4, 9],
    [3, 40, 1, 1],
])

b1 = [1200, 800]

ineq1 = ["<=", "<="]

In [4]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1)

==================== Simplex Method ====================
####################
Iteration 1. s2 --> x2
--------------------
[[ 6.25   0.     3.75   8.75   1.    -0.25 ]
 [ 0.075  1.     0.025  0.025  0.     0.025]] 

    Basis
s1    0.0
x2  100.0
Solution [   0.   20.    0.    0. 1000.    0.] 	Z: 2000.00 

####################
Iteration 2. s1 --> x4
--------------------
[[ 0.714  0.     0.429  1.     0.114 -0.029]
 [ 0.057  1.     0.014  0.    -0.003  0.026]] 

    Basis
x4   50.0
x2  100.0
Solution [  0.     17.143   0.    114.286   0.      0.   ] 	Z: 7428.57 

####################
Iteration 3. x4 --> x3
--------------------
[[ 1.667  0.     1.     2.333  0.267 -0.067]
 [ 0.033  1.     0.    -0.033 -0.007  0.027]] 

    Basis
x3   30.0
x2  100.0
Solution [  0.     13.333 266.667   0.      0.      0.   ] 	Z: 9333.33 

####################
Optimal solution found in 3 iterations
      Solution
x1    0.000000
x2   13.333333
x3  266.666667
x4    0.000000
s1    0.000000
s2    0.000000

Optima