# Example 02

$$\max Z = -x_1 + 2x_2 - x_3 $$

\begin{align*}
3x_1 + x_2 - x_3 &\leq 10\\
-x_1 + 4x_2 + x_3 &\geq 6\\
  x_2 + x_3 &\leq 4\\[5mm]  
x_1 , x_2, x_3 &\geq 0
\end{align*}

In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [2]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [3]:
cj1 = [-1, 2, -1]

A1 = np.array([
    [3,1,-1],
    [-1,4,1],
    [0,1,1]
])

b1 = [10,6,4]

ineq1 = ["<=", ">=", "<="]

In [16]:
sol1, z1, lastrow1, optitable = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1)

==================== Simplex Method ====================
####################
Iteration 1. A2 --> x2
--------------------
[[ 3.25  0.   -1.25  1.    0.25 -0.25  0.  ]
 [-0.25  1.    0.25  0.   -0.25  0.25  0.  ]
 [ 0.25  0.    0.75  0.    0.25 -0.25  1.  ]] 

    Basis
s1    0.0
x2    2.0
s3    0.0
Solution [0.  1.5 0.  8.5 0.  0.  2.5] 	Z: 3.00 

####################
Iteration 2. s3 --> s2
--------------------
[[ 3.  0. -2.  1.  0.  0. -1.]
 [ 0.  1.  1.  0.  0.  0.  1.]
 [ 1.  0.  3.  0.  1. -1.  4.]] 

    Basis
s1    0.0
x2    2.0
s2    0.0
Solution [ 0.  4.  0.  6. 10.  0.  0.] 	Z: 8.00 

####################
Optimal solution found in 2 iterations
    Solution
x1       0.0
x2       4.0
x3       0.0
s1       6.0
s2      10.0
A2       0.0
s3       0.0

Optimal Table:
     Cb   x1   x2   x3   s1   s2   A2   s3     b
s1  0.0  3.0  0.0 -2.0  1.0  0.0  0.0 -1.0   6.0
x2  2.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0   4.0
s2  0.0  1.0  0.0  3.0  0.0  1.0 -1.0  4.0  10.0

Row Base:
          x1

### $c_j - Z_j$

In [5]:
print(lastrow1)

[[    0.     2.     2.     0.     0.     0.     2.]
 [   -1.     0.    -3.     0.     0. -1000.    -2.]]


In [202]:
B = A[:2, :2]
Binv = np.linalg.inv(B)
print(B)
print(Binv)

[[ 1  2]
 [ 2 -1]]
[[ 0.2  0.4]
 [ 0.4 -0.2]]


In [203]:
b2 = np.array([7, 2])
b3 = np.array([3, 9])

In [204]:
print(Binv.dot(b2))
print(Binv.dot(b3))

[2.2 2.4]
[ 4.2 -0.6]


In [10]:
cjdual = b1

Adual = A1.T

bdual = cj1

ineqdual = [">=", "<=", ">="]

In [11]:
soldual, wvalues, lastdualrow, tabledual = simplex(matrix=Adual, 
                                                   rhs=bdual, 
                                                   z=cjdual, 
                                                   inequalities=ineqdual, 
                                                   direction=-1, vlabel="y")

==================== Simplex Method ====================
####################
Iteration 1. A1 --> y1
--------------------
[[ 1.    -0.333  0.    -0.333  0.333  0.     0.     0.   ]
 [ 0.     4.333  1.     0.333 -0.333  1.     0.     0.   ]
 [ 0.     0.667  1.    -0.333  0.333  0.    -1.     1.   ]] 

     Basis
y1    10.0
s2     0.0
A3  1000.0
Solution [-0.333  0.     0.     0.     0.     2.333  0.    -1.333] 	Z: -1336.67 

####################
Iteration 2. A3 --> y3
--------------------
[[ 1.    -0.333  0.    -0.333  0.333  0.     0.     0.   ]
 [ 0.     3.667  0.     0.667 -0.667  1.     1.    -1.   ]
 [ 0.     0.667  1.    -0.333  0.333  0.    -1.     1.   ]] 

    Basis
y1   10.0
s2    0.0
y3    4.0
Solution [-0.333  0.    -1.333  0.     0.     3.667  0.     0.   ] 	Z: -8.67 

####################
Optimal solution found in 2 iterations
    Solution
y1 -0.333333
y2  0.000000
y3 -1.333333
s1  0.000000
A1  0.000000
s2  3.666667
s3  0.000000
A3  0.000000

Optimal Table:
      Cb   y1  

In [12]:
print(lastdualrow)


[[  10.      -0.667    4.      -4.667    4.667    0.      -4.       4.   ]
 [  -0.      -6.667   -0.      -4.667 -995.333   -0.      -4.    -996.   ]]


In [ ]:
B = np.array([[1,1,0], [0,4,-1], []])