# Example 04

$$\max Z = -x_1 + 2x_2 - x_3 $$

\begin{align*}
3x_1 + x_2 - x_3 &\leq 10\\
-x_1 + 4x_2 + x_3 &\geq 6\\
x_2 + x_3& \leq 4\\[5mm]  
x_1 , x_2, x_3 &\geq 0
\end{align*}

In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [2]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [3]:
cj1 = [-1, 2, -1]

A1 = np.array([
    [3, 1, -1],
    [-1, 4, 1],
    [0, 1, 1],
])

b1 = [10, 6, 4]

ineq1 = ["<=", ">=", "<="]

In [4]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1)

==================== Simplex Method ====================
####################
Iteration 1. A2 --> x2
--------------------
[[ 3.25  0.   -1.25  1.    0.25 -0.25  0.  ]
 [-0.25  1.    0.25  0.   -0.25  0.25  0.  ]
 [ 0.25  0.    0.75  0.    0.25 -0.25  1.  ]] 

    Basis
s1    0.0
x2    2.0
s3    0.0
Solution [0.  1.5 0.  8.5 0.  0.  2.5] 	Z: 3.00 

####################
Iteration 2. s3 --> s2
--------------------
[[ 3.  0. -2.  1.  0.  0. -1.]
 [ 0.  1.  1.  0.  0.  0.  1.]
 [ 1.  0.  3.  0.  1. -1.  4.]] 

    Basis
s1    0.0
x2    2.0
s2    0.0
Solution [ 0.  4.  0.  6. 10.  0.  0.] 	Z: 8.00 

####################
Optimal solution found in 2 iterations
    Solution
x1       0.0
x2       4.0
x3       0.0
s1       6.0
s2      10.0
A2       0.0
s3       0.0

Optimal Table:
     Cb   x1   x2   x3   s1   s2   A2   s3     b
s1  0.0  3.0  0.0 -2.0  1.0  0.0  0.0 -1.0   6.0
x2  2.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0   4.0
s2  0.0  1.0  0.0  3.0  0.0  1.0 -1.0  4.0  10.0

Row Base:
          x1