# Example 03

$$\max Z = 4x_1 + 6x_2 + 2x_3 $$

\begin{align*}
x_1 + x_2 + x_3 &\leq 3\\
x_1 + 4x_2 + 7x_3&\leq 9\\[5mm]  
x_1 , x_2, x_3 &\geq 0
\end{align*}

In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3, suppress=True)

In [2]:
%run "../auxfunc/algorithms.ipynb"
%run "../auxfunc/fullmatrix.ipynb"

In [3]:
cj1 = [4, 6, 2]

A1 = np.array([
    [1, 1, 1],
    [1, 4, 7],
])

b1 = [3, 9]

ineq1 = ["<=", "<="]

In [4]:
sol1, z1, lastrow11, optitable11 = simplex(matrix=A1,
                                        rhs=b1, 
                                        z=cj1, 
                                        inequalities=ineq1)

==================== Simplex Method ====================
####################
Iteration 1. s2 --> x2
--------------------
[[ 0.75  0.   -0.75  1.   -0.25]
 [ 0.25  1.    1.75  0.    0.25]] 

    Basis
s1    0.0
x2    6.0
Solution [0.   2.25 0.   0.75 0.  ] 	Z: 13.50 

####################
Iteration 2. s1 --> x1
--------------------
[[ 1.     0.    -1.     1.333 -0.333]
 [ 0.     1.     2.    -0.333  0.333]] 

    Basis
x1    4.0
x2    6.0
Solution [1. 2. 0. 0. 0.] 	Z: 16.00 

####################
Optimal solution found in 2 iterations
    Solution
x1       1.0
x2       2.0
x3       0.0
s1       0.0
s2       0.0

Optimal Table:
     Cb   x1   x2   x3        s1        s2    b
x1  4.0  1.0  0.0 -1.0  1.333333 -0.333333  1.0
x2  6.0  0.0  1.0  2.0 -0.333333  0.333333  2.0

Row Base:
          x1   x2   x3        s1        s2
zj       4.0  6.0  8.0  3.333333  0.666667
cj - zj  0.0  0.0 -6.0 -3.333333 -0.666667
