# Example 03-36

La persona quiere decidir los componentes de una dieta que cumpla con sus requerimientos diarios de proteínas, grasas y carbohidratos al costo mínimo. La elección debe hacerse a partir de cuatro tipos diferentes de alimentos. Los rendimientos por unidad de estos alimentos se dan en la tabla siguiente. Formule un modelo de programación lineal para el problema y resuelva por método simplex.

|Comida| Proteinas | Grasas | Carbohidratos | Cost
|-----|---|---|-----|---|
1|3|2|6|45|
2|4|2|4|40|
3|8|7|7|85|
4|6|5|4|65|
Requrimiento| | | |
Mínimo| 800|200 | 700|

## Model

$$\min Z = 45x_1 + 40x_2 + 85x_3 + 65x_4 $$

\begin{align*}
3x_1 + 4x_2 +  8x_3  + 6x_4 & \geq 800\\
2x_1 + 2x_2 +  7x_3  + 5x_4 & \geq 200\\
6x_1 + 4x_2 +  7x_3 + 4x_4 & \geq 700\\[5mm]
x_1, x_2,x_3, x_4 & \geq 0
\end{align*}

## Dual Formulation

$$ \max 800y_1 +  200y_2 + 700x_3 $$

\begin{align*}
3y_1 + 2y_2 + 6y_3 &\leq 45\\
4y_1 + 2y_2 + 4y_3 &\leq 40\\
8y_1 + 7y_2 + 7y_3 &\leq 85\\
6y_1 + 5y_2 + 4y_3 &\leq 65\\[5mm]
y_1, y_2,y_3 & \geq 0
\end{align*}




## Dual Formulation Standard Form

$$ \max 800y_1 +  200y_2 + 700x_3 $$

\begin{align*}
3y_1 + 2y_2 + 6y_3 + s_1&= 45\\
4y_1 + 2y_2 + 4y_3 + s_2&= 40\\
8y_1 + 7y_2 + 7y_3 + s_3&= 85\\
6y_1 + 5y_2 + 4y_3 + s_4&= 65\\[5mm]
y_1, y_2,y_3, s_1, s_2,s_3, s_4 & \geq 0
\end{align*}




In [184]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [185]:
%run "simplex_algorithm.ipynb"

In [186]:
cj = np.array([800, 200, 700, 0, 0, 0, 0], dtype=float)

A = np.array([
    [3,2,6, 1, 0, 0, 0],
    [4,2,4, 0, 1, 0, 0],
    [8,7,7, 0, 0, 1, 0],
    [6,5,4, 0, 0, 0, 1],
], dtype=float)

b = np.array([45, 40, 85, 65], dtype=float)


In [187]:
solsdual, wvalues = simplex(matrix=A, rhs=b, z=cj, numxvars=3, direction=1)

Iteration 1
[[ 0.    0.5   3.    1.   -0.75  0.    0.  ]
 [ 1.    0.5   1.    0.    0.25  0.    0.  ]
 [ 0.    3.   -1.    0.   -2.    1.    0.  ]
 [ 0.    2.   -2.    0.   -1.5   0.    1.  ]] 

Solution [10.  0.  0. 15.  0.  5.  5.] 	Z: 8000.00 

Optimal solution found in 1 iterations
Solution
[[ 800.  400.  800.    0.  200.    0.    0.]
 [   0. -200. -100.    0. -200.    0.    0.]
 [  10.    0.    0.   15.    0.    5.    5.]]


In [189]:
cj2 = np.array([45, 40, 85, 65, 0, 0, 0, 10000, 10000, 10000], dtype=float)

A2 = np.array([
    [3, 4, 8, 6, -1,   0,   0, 1, 0, 0],
    [2, 2, 7, 5,  0,  -1,   0, 0, 1, 0],
    [6, 4, 7, 4,  0,   0,  -1, 0, 0, 1],
], dtype=float)

b2 = np.array([
    800,
    200,
    700,
], dtype=float)

In [190]:
solsprimal, zvalues = simplex(matrix=A2, rhs=b2, z=cj2, numxvars=4, direction=-1)

Iteration 1
[[ 0.714  1.714  0.     0.286 -1.     1.143  0.     1.    -1.143  0.   ]
 [ 0.286  0.286  1.     0.714  0.    -0.143  0.     0.     0.143  0.   ]
 [ 4.     2.     0.    -1.     0.     1.    -1.     0.    -1.     1.   ]] 

Solution [  0.      0.     28.571   0.      0.      0.      0.    571.429   0.
 500.   ] 	Z: 10716714.29 

Iteration 2
[[  0.    1.   -2.5  -1.5  -1.    1.5   0.    1.   -1.5   0. ]
 [  1.    1.    3.5   2.5   0.   -0.5   0.    0.    0.5   0. ]
 [  0.   -2.  -14.  -11.    0.    3.   -1.    0.   -3.    1. ]] 

Solution [100.   0.   0.   0.   0.   0.   0. 500.   0. 100.] 	Z: 6004500.00 

Iteration 3
[[ 0.     2.     4.5    4.    -1.     0.     0.5    1.     0.    -0.5  ]
 [ 1.     0.667  1.167  0.667  0.     0.    -0.167  0.     0.     0.167]
 [ 0.    -0.667 -4.667 -3.667  0.     1.    -0.333  0.    -1.     0.333]] 

Solution [116.667   0.      0.      0.      0.     33.333   0.    450.      0.
   0.   ] 	Z: 4505250.00 

Iteration 4
[[ 0.     0.444  1.     0