In [1]:
import numpy as np

In [2]:
A = np.array([
    [2, 3, 3, 1, 0],
    [1, 2, 1, 0, 1],
])

In [3]:
cj = np.array([6, 3, 4, -2, 1])

In [5]:
print(np.where(A == 1))

(array([0, 1, 1, 1], dtype=int64), array([3, 0, 2, 4], dtype=int64))


In [60]:
cj2 = np.array([5, 12, 4, 0, -1000])

A2 = np.array([
    [0, 1, -1/5, 2/5, -1/5],
    [1, 0, 7/5, 1/5, 2/5],
], dtype=float)

In [61]:
print(A2)

[[ 0.   1.  -0.2  0.4 -0.2]
 [ 1.   0.   1.4  0.2  0.4]]


In [62]:
cbindex = np.where((A2 == 1) & (np.abs(A2).sum(axis=0) == 1))[1]
cb = cj2[cbindex]
print(cb)

[12  5]


In [14]:
%run "fullmatrix.ipynb"

In [18]:
cj = [40, 25, 50]

A = np.array([
    [1, 2, 1],
    [2, 1, 4],
    [2, 5, 1],
])

b = [36, 60, 45]

ineq = [">="] * 3


In [19]:
full_matrix, full_labels, cj = create_fullmatrix(body=A, inequalities=ineq, c=cj, varlabel="x", direction=1, M=1000 )

In [33]:
print(full_matrix)

[[ 1.  2.  1. -1.  1.  0.  0.  0.  0.]
 [ 2.  1.  4.  0.  0. -1.  1.  0.  0.]
 [ 2.  5.  1.  0.  0.  0.  0. -1.  1.]]


In [34]:
print(np.where(full_matrix == 1))

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64), array([0, 2, 4, 1, 6, 2, 8], dtype=int64))


In [36]:
np.where((full_matrix == 1) & (np.abs(full_matrix).sum(axis=0) == 1))

(array([0, 1, 2], dtype=int64), array([4, 6, 8], dtype=int64))

In [39]:
print(full_matrix == 1)

[[ True False  True False  True False False False False]
 [False  True False False False False  True False False]
 [False False  True False False False False False  True]]


In [45]:
np.where((full_matrix == 1).sum(axis=0) == 1) 

(array([0, 1, 4, 6, 8], dtype=int64),)

In [41]:
np.where(np.abs(full_matrix).sum(axis=0) == 1)

(array([3, 4, 5, 6, 7, 8], dtype=int64),)

In [46]:
np.where(full_matrix == 1)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 4, 1, 6, 2, 8], dtype=int64))