# Example 03-36

$$\min Z = 45x_1 + 40x_2 + 85x_3 + 65x_4 $$

\begin{align*}
3x_1 + 4x_2 +  8x_3  + 6x_4 & \geq 800\\
2x_1 + 2x_2 +  7x_3  + 5x_4 & \geq 200\\
6x_1 + 4x_2 +  7x_3 + 4x_4 & \geq 700\\[5mm]
x_1, x_2,x_3, x_4 & \geq 0
\end{align*}

In [142]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [143]:
%run "simplex_algorithm.ipynb"
%run "twophase_method.ipynb"

In [144]:
cj = np.array([45, 40, 85, 65, 0, 0, 0, 10000, 10000, 10000], dtype=float)

A = np.array([
    [3, 4, 8, 6, -1,   0,   0, 1, 0, 0],
    [2, 2, 7, 5,  0,  -1,   0, 0, 1, 0],
    [6, 4, 7, 4,  0,   0,  -1, 0, 0, 1],
], dtype=float)

b = np.array([
    800,
    200,
    700,
], dtype=float)

In [145]:
sol1, z1 = simplex(matrix=A, rhs=b, z=cj, numxvars=4, direction=-1)
print(sol1.shape)

Iteration 1
[[ 0.714  1.714  0.     0.286 -1.     1.143  0.     1.    -1.143  0.   ]
 [ 0.286  0.286  1.     0.714  0.    -0.143  0.     0.     0.143  0.   ]
 [ 4.     2.     0.    -1.     0.     1.    -1.     0.    -1.     1.   ]] 

Solution [  0.      0.     28.571   0.      0.      0.      0.    571.429   0.
 500.   ] 	Z: 10716714.29 

Iteration 2
[[  0.    1.   -2.5  -1.5  -1.    1.5   0.    1.   -1.5   0. ]
 [  1.    1.    3.5   2.5   0.   -0.5   0.    0.    0.5   0. ]
 [  0.   -2.  -14.  -11.    0.    3.   -1.    0.   -3.    1. ]] 

Solution [100.   0.   0.   0.   0.   0.   0. 500.   0. 100.] 	Z: 6004500.00 

Iteration 3
[[ 0.     2.     4.5    4.    -1.     0.     0.5    1.     0.    -0.5  ]
 [ 1.     0.667  1.167  0.667  0.     0.    -0.167  0.     0.     0.167]
 [ 0.    -0.667 -4.667 -3.667  0.     1.    -0.333  0.    -1.     0.333]] 

Solution [116.667   0.      0.      0.      0.     33.333   0.    450.      0.
   0.   ] 	Z: 4505250.00 

Iteration 4
[[ 0.     0.444  1.     0

In [146]:
sols2, z2 = twophase(matrix=A, rhs=b, z=cj, numxvars=4, direction=-1)

============================== PHASE I ============================== 

Iteration 1
[[ 0.714  1.714  0.     0.286 -1.     1.143  0.     1.    -1.143  0.   ]
 [ 0.286  0.286  1.     0.714  0.    -0.143  0.     0.     0.143  0.   ]
 [ 4.     2.     0.    -1.     0.     1.    -1.     0.    -1.     1.   ]] 

Solution [  0.      0.     28.571   0.      0.      0.      0.    571.429   0.
 500.   ] 	Z: 1071.43 

Iteration 2
[[  0.    1.   -2.5  -1.5  -1.    1.5   0.    1.   -1.5   0. ]
 [  1.    1.    3.5   2.5   0.   -0.5   0.    0.    0.5   0. ]
 [  0.   -2.  -14.  -11.    0.    3.   -1.    0.   -3.    1. ]] 

Solution [100.   0.   0.   0.   0.   0.   0. 500.   0. 100.] 	Z: 600.00 

Iteration 3
[[ 0.     2.     4.5    4.    -1.     0.     0.5    1.     0.    -0.5  ]
 [ 1.     0.667  1.167  0.667  0.     0.    -0.167  0.     0.     0.167]
 [ 0.    -0.667 -4.667 -3.667  0.     1.    -0.333  0.    -1.     0.333]] 

Solution [116.667   0.      0.      0.      0.     33.333   0.    450.      0.


In [147]:
print(sols2)

[[  0.      0.     28.571   0.      0.      0.      0.    571.429   0.
  500.   ]
 [100.      0.      0.      0.      0.      0.      0.    500.      0.
  100.   ]
 [116.667   0.      0.      0.      0.     33.333   0.    450.      0.
    0.   ]
 [  0.      0.    100.      0.      0.    500.      0.      0.      0.
    0.   ]
 [  0.      0.    100.      0.      0.    500.      0.      0.      0.
    0.   ]
 [  0.    125.      0.     50.      0.    300.      0.      0.      0.
    0.   ]
 [  0.    200.      0.      0.      0.    200.    100.      0.      0.
    0.   ]]
